<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Browser launched success]]>
    </line>
    <line>
      <![CDATA[screenShot taken for TC validateUserName]]>
    </line>
    <line>
      <![CDATA[Logging out]]>
    </line>
    <line>
      <![CDATA[Browser closed sucusses]]>
    </line>
  </reporter-output>
  <suite started-at="2022-04-04T07:49:39 IST" name="Default suite" finished-at="2022-04-04T07:49:48 IST" duration-ms="8984">
    <groups>
    </groups>
    <test started-at="2022-04-04T07:49:39 IST" name="Default test" finished-at="2022-04-04T07:49:48 IST" duration-ms="8984">
      <class name="KiteAppTest.KiteUserNameValidation1">
        <test-method is-config="true" signature="browserLaunch()[pri:0, instance:KiteAppTest.KiteUserNameValidation1@79924b]" started-at="2022-04-04T07:49:39 IST" name="browserLaunch" finished-at="2022-04-04T07:49:43 IST" duration-ms="3761" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser launched success]]>
            </line>
          </reporter-output>
        </test-method> <!-- browserLaunch -->
        <test-method is-config="true" signature="loginToKiteApp()[pri:0, instance:KiteAppTest.KiteUserNameValidation1@79924b]" started-at="2022-04-04T07:49:43 IST" name="loginToKiteApp" finished-at="2022-04-04T07:49:44 IST" duration-ms="1176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToKiteApp -->
        <test-method signature="validateUserName()[pri:0, instance:KiteAppTest.KiteUserNameValidation1@79924b]" started-at="2022-04-04T07:49:44 IST" name="validateUserName" finished-at="2022-04-04T07:49:45 IST" duration-ms="1051" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because the return value of "org.apache.poi.ss.usermodel.Row.getCell(int)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because the return value of "org.apache.poi.ss.usermodel.Row.getCell(int)" is null
at utility.Utility.readDataFromExcel(Utility.java:26)
at KiteAppTest.KiteUserNameValidation1.validateUserName(KiteUserNameValidation1.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[screenShot taken for TC validateUserName]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateUserName -->
        <test-method is-config="true" signature="logoutFromKiteApp()[pri:0, instance:KiteAppTest.KiteUserNameValidation1@79924b]" started-at="2022-04-04T07:49:46 IST" name="logoutFromKiteApp" finished-at="2022-04-04T07:49:48 IST" duration-ms="2457" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logging out]]>
            </line>
          </reporter-output>
        </test-method> <!-- logoutFromKiteApp -->
        <test-method is-config="true" signature="clossingBrowser()[pri:0, instance:KiteAppTest.KiteUserNameValidation1@79924b]" started-at="2022-04-04T07:49:48 IST" name="clossingBrowser" finished-at="2022-04-04T07:49:48 IST" duration-ms="139" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser closed sucusses]]>
            </line>
          </reporter-output>
        </test-method> <!-- clossingBrowser -->
      </class> <!-- KiteAppTest.KiteUserNameValidation1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
